// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABtn: typeof import('anu-vue')['ABtn']
    AChip: typeof import('anu-vue')['AChip']
    ADrawer: typeof import('anu-vue')['ADrawer']
    AInput: typeof import('anu-vue')['AInput']
    ASwitch: typeof import('anu-vue')['ASwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
