/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('anu-vue')['AAlert']
    ABtn: typeof import('anu-vue')['ABtn']
    AChip: typeof import('anu-vue')['AChip']
    ADrawer: typeof import('anu-vue')['ADrawer']
    AInput: typeof import('anu-vue')['AInput']
    ASwitch: typeof import('anu-vue')['ASwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDrawer: typeof import('./components/TheDrawer.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
